### ISSUE TITLE
远景

### ISSUE THREAD

**Issue by Solmonz** [iXinjie/qlScripts#1]
老哥 这个远景论坛的签到怎么移到青龙里面使用的呀

**Comment by yuan-xinjie** [comment]
拉库命令
`ql repo https://github.com/iXinjie/qlScripts.git "pcbeta_" "" ""`
脚本文件中的cookies值要换成自己的

**Comment by Solmonz** [comment]
好的，感恩

**Comment by Solmonz** [comment]
但是这个推送，好像有点问题

**Comment by Solmonz** [comment]
大佬，这个推送，没办法推送，他只能打印日志出来，可以修改的嘛

**Comment by yuan-xinjie** [comment]
你用什么方式推送，以前我推送过一段时间，后来反正我也天天进面板，顺便也看了

**Comment by Solmonz** [comment]
Tg bot

**Comment by Solmonz** [comment]
老哥有Tg嘛，可以加个好友

**Comment by yuan-xinjie** [comment]
tg我基本不怎么玩，等我研究一下接口，看看怎么实现

**Comment by Solmonz** [comment]
好嘞，大佬有别的联系方式吗？可以添加您一下，方便请教一下，关于签到的一些问题

**Comment by iXinjie** [comment]
vx吧，solitudeym7

**Comment by Solmonz** [comment]
1
